### ISSUE TITLE
 Landmark3d260k的一些咨询

### ISSUE THREAD

**Issue by yaolp123** [ZHEQIUSHUI/Landmark3d260k#1]
Github作者：
   您好！您工程里面的数据集以及pfld.getmodel()函数在哪呢？这个工程是不是提取人脸区域，使用人脸特征landmark算法模型，然后得到lmk，这个是用来三维重建的吗？ 期待您的回复，  谢谢！

**Comment by ZHEQIUSHUI** [comment]
demo代码只是演示怎么前后处理的 我附带了onnx的模型，可以根据demo代码改一个onnx推理代码

不是用来做三维重建的 只是用做头部姿态以及3d landmark检测

**Comment by ZHEQIUSHUI** [comment]
模型也是瞎训的
